meta_product_name: 'Emerge'
meta_title: 'What is emerging'
meta_description: 'Emerge is an independent, non-profit media platform aiming to explore the emerging cultural narratives of our time.'
meta_image: 'app/assets/images/Emerge_Logo.jpg'
twitter_account: '@whatisemerging'
card_type: 'summary_large_image'
